version: '3'
services: 
    app:
        container_name: node-email-conf
        restart: always
        build: .
        ports: 
            - '8080:8080'
        links: 
            - mongodb
    mongodb:
        container_name: mongo
        image: mongo
        ports: 
            - '27017:27017'